name: Build Debug Flutter App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    env:
      FLUTTER_VERSION: '3.19.4'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Updated to use Node.js 20

      - name: Set up Flutter
        uses: actions/checkout@v3 # Updated to use Node.js 20
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android Debug APK
        run: flutter build apk --debug

      - name: Build iOS Debug
        run: flutter build ios --debug

      - name: Upload Android Debug APK to Artifacts
        uses: actions/upload-artifact@v3 # Updated to use Node.js 20
        with:
          name: android-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Upload iOS Debug Build to Artifacts
        uses: actions/upload-artifact@v3 # Updated to use Node.js 20
        with:
          name: ios-debug-build
          path: build/ios/iphoneos/Runner.app
