name: build flutter app release

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

#      - run: flutter pub get
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install dependencies
        run: flutter pub get

      - name: Ensure gradle wrapper is compatible
        run: |
          sed -i.bak 's/distributionUrl=https\:\/\/services.gradle.org\/distributions\/gradle-.*-all.zip/distributionUrl=https\:\/\/services.gradle.org\/distributions\/gradle-7.3.3-all.zip/' android/gradle/wrapper/gradle-wrapper.properties

      - run: flutter build apk --release

      - run: pod repo update
        working-directory: ios

      - run: flutter build ios --release --no-codesign

      - name: Upload Android APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload iOS Debug Build to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          path: build/ios/iphoneos/Runner.app
          tag: v1.0
          overwrite: true
          body: "This is first release"